### ISSUE TITLE
merging adds projectiles instead of merging

### ISSUE THREAD

**Issue by SamuelJamuelTheSecond** [GrahamKracker/OmegaCrosspathing#11]
i don't know if this is intended, but when i try to merge ANY tower with any other tower, it only adds the projectile to the attack. when i merged dart monkey with 1-0-0 wizard monkey, it only changed the range and got a second projectile

**Comment by GrahamKracker** [comment]
ok? thats how the algorithm works

**Comment by SamuelJamuelTheSecond** [comment]
oh, i thought that was a bug lol
